apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sysctl/mm.transparent_hugepage.enabled
                operator: In
                values:
                - "never"
              - key: sysctl/mm.transparent_hugepage.defrag
                operator: In
                values:
                - "never"
      containers:
      - name: redis
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 150m
            memory: 256Mi
