apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-exposed
  labels:
    app: redis-exposed
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: sysctl/mm.transparent_hugepage.enabled
                    operator: In
                    values:
                      - "never"
                  - key: sysctl/mm.transparent_hugepage.defrag
                    operator: In
                    values:
                      - "never"
      containers:
        - name: redis-exposed
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 256Mi
