apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drone-vault
  name: drone-vault
  namespace: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-vault
  template:
    metadata:
      labels:
        app: drone-vault
    spec:
      containers:
        - name: drone-vault
          image: drone/vault:1.1.0
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 250m
          env:
            - name: DRONE_DEBUG
              value: "true"
            - name: DRONE_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-vault
                  key: DRONE_SECRET
            - name: VAULT_ADDR
              value: "https://vault.muwazana.com"
            - name: VAULT_TOKEN_TTL
              value: "72h"
            - name: VAULT_TOKEN_RENEWAL
              value: "24h"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: drone-vault
                  key: VAULT_TOKEN
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 2
