apiVersion: v1
kind: Service
metadata:
  name: redis-exposed
  labels:
    app: redis-exposed
spec:
  loadBalancerIP: 35.234.128.141
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis-exposed
  type: LoadBalancer
