apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tardis-machine
  labels:
    app: tardis-machine
spec:
  template:
    spec:
      containers:
        - name: tardis-machine
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
          # resources:
          #   limits:
          #     cpu: 1000m
          #     memory: 2Gi
          #   requests:
          #     cpu: 500m
          #     memory: 500Mi
