---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alerts
  labels:
    app: alerts
data:
  LOG_LEVEL: "INFO"
  REDIS_NODE_ADDR: "redis"
  REDIS_NODE_TCP_PORT: "6379"
  EXP_REDIS_NODE_ADDR: "redis-exposed.ftx.dev.muwazana.com"
  EXP_REDIS_NODE_TCP_PORT: "6379"
  COREPACK_FAMILIES: "f.mrd.pilot"
  F_MRD_PILOT: "BTC-0626"
