---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tardis-machine
  labels:
    app: tardis-machine
spec:
  # replicas: 120
  selector:
    matchLabels:
      app: tardis-machine
  template:
    metadata:
      labels:
        app: tardis-machine
    spec:
      containers:
        - name: tardis-machine
          env:
            - name: LOG_LEVEL
              value: INFO
          envFrom:
            - configMapRef:
                name: tardis-machine
                optional: true
            - secretRef:
                name: tardis-machine
                optional: true
          image: tardisdev/tardis-machine:3.2.1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
      # nodeSelector:
      #   cloud.google.com/gke-nodepool: node-pool-tardis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: tardis-machine
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: tardis-machine
