apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0
        ports:
        - name: redis
          containerPort: 6379
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: redis
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: redis
