---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  labels:
    app: ${SERVICE_NAME}
spec:
  template:
    spec:
      containers:
        - name: ${SERVICE_NAME}
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 128Mi
